stages:
  - linting

phpcs:
  stage: linting
  image: registry.gitlab.com/pipeline-components/php-codesniffer:latest
  script: |
    set +euo pipefail  # don't abort if any following command fails
    phpcs -q --report=junit > logs/phpcs-junit.xml
  artifacts:
    when: always
    paths:
      - logs/phpcs-junit.xml
    reports:
      junit: logs/phpcs-junit.xml
